name: Build TWRP for caymanlm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update

        # Основні пакети
        sudo apt-get install -y \
          bc bison build-essential ccache curl flex git kmod liblz4-tool \
          libssl-dev lzop pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev imagemagick device-tree-compiler \
          openjdk-8-jdk android-sdk-libsparse-utils repo \
          libncurses-dev libtinfo-dev libncursesw5-dev || true

        # Fallback на новіші версії
        sudo apt-get install -y \
          libncurses6 libncursesw6 libtinfo6 || true

    - name: Init repo
      run: |
        mkdir ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-13.0
        repo sync --force-sync --no-tags --no-clone-bundle

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Build TWRP
      run: |
        cd ~/twrp
        . build/envsetup.sh
        lunch omni_caymanlm-eng
        mka recoveryimage

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-caymanlm
        path: ~/twrp/out/target/product/caymanlm/recovery.img
