name: Build TWRP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex           git gnupg gperf libxml2-utils lzop pngcrush rsync schedtool           squashfs-tools xsltproc zip zlib1g-dev imagemagick device-tree-compiler           openjdk-8-jdk wget python3 python-is-python3

    - name: Initialize Repo
      run: |
        mkdir ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1 --no-tags

    - name: Sync Repo
      run: |
        cd ~/twrp
        repo sync -j$(nproc) --force-sync

    - name: Clone Device Tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Build TWRP
      run: |
        cd ~/twrp
        . build/envsetup.sh
        lunch twrp_caymanlm-eng
        mka recoveryimage

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: ~/twrp/out/target/product/caymanlm/recovery.img
