
name: Build TWRP (minimal)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core bc curl zip unzip tar repo python-is-python3 openjdk-11-jdk

    - name: Set up working directory
      run: |
        mkdir -p ~/twrp
        cd ~/twrp

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Clone TWRP minimal manifest manually
      run: |
        cd ~/twrp
        mkdir .repo
        git clone https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git .repo/manifests -b twrp-12.1
        touch .repo/local_manifests.xml

    - name: Build TWRP (stub)
      run: |
        echo "Build step placeholder"
        ls -la ~/twrp/device/lge/caymanlm

    - name: Upload dummy artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-dummy
        path: ~/twrp/device/lge/caymanlm
