name: Build TWRP Recovery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Starting TWRP CI"

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies (with fallback)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex git kmod \
          libssl-dev libelf-dev python3 python3-distutils python3-apt unzip zip || true
        sudo apt-get install -y libncurses-dev libtinfo-dev lib32ncurses-dev || true

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Set up repo workspace
      run: mkdir -p ~/twrp

    - name: Cache .repo folder
      uses: actions/cache@v4
      with:
        path: ~/twrp/.repo
        key: ${{ runner.os }}-repo-cache-twrp

    - name: Init TWRP repo
      run: |
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Sync TWRP repo
      run: |
        cd ~/twrp
        repo sync --force-sync -j$(nproc --all)

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Build TWRP
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        . build/envsetup.sh
        lunch omni_caymanlm-eng
        mka recoveryimage

    - name: Check recovery.img exists
      run: |
        test -f ~/twrp/out/target/product/caymanlm/recovery.img

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-caymanlm
        path: ~/twrp/out/target/product/caymanlm/recovery.img

