name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential curl flex git gnupg gperf imagemagick \
            lib32z1-dev liblz4-tool libncurses5-dev libncurses-dev \
            libssl-dev libxml2 libxml2-utils lzop pngcrush rsync \
            schedtool squashfs-tools xsltproc zip zlib1g-dev \
            openjdk-11-jdk python-is-python3

          # fallback для ncurses, якщо не знайдені
          sudo apt-get install -y libncurses5 || echo "libncurses5 not found, continuing..."
          sudo apt-get install -y lib32ncurses5 || echo "lib32ncurses5 not found, continuing..."

      - name: Set up repo
        run: |
          mkdir ~/twrp && cd ~/twrp
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod a+x repo
          sudo mv repo /usr/local/bin/

      - name: Init repo
        run: |
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

      - name: Sync repo
        run: |
          cd ~/twrp
          repo sync --force-sync

      - name: Cache .repo
        uses: actions/cache@v4
        with:
          path: ~/twrp/.repo
          key: ${{ runner.os }}-twrp-repo-cache
          restore-keys: |
            ${{ runner.os }}-twrp-

