name: Build TWRP Recovery

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex \
            git gnupg gperf libncurses5-dev libssl-dev libxml2-utils \
            lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev \
            python-is-python3 openjdk-11-jdk repo imagemagick

      - name: Set up repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up repo workspace
        run: mkdir -p ~/twrp

      - name: Cache .repo folder
        uses: actions/cache@v4
        with:
          path: ~/twrp/.repo
          key: ${{ runner.os }}-twrp-${{ hashFiles('.github/workflows/build-twrp.yml') }}
          restore-keys: |
            ${{ runner.os }}-twrp-

      - name: Init TWRP repo
        run: |
          cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1

      - name: Sync TWRP repo
        run: |
          cd ~/twrp
          repo sync --force-sync -j$(nproc --all)

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_caymanlm-eng
          mka recoveryimage

      - name: Check recovery.img exists
        run: test -f ~/twrp/out/target/product/caymanlm/recovery.img

      - name: Upload recovery image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-recovery
          path: ~/twrp/out/target/product/caymanlm/recovery.img