name: Build TWRP with fallback deps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies with fallback
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update

        install_or_skip() {
          if apt-cache show "$1" > /dev/null 2>&1; then
            echo "Installing $1"
            sudo apt-get install -y "$1"
          else
            echo "Skipping $1 — not available"
          fi
        }

        install_or_skip libncurses5-dev
        install_or_skip libncursesw5-dev
        install_or_skip libncurses6
        install_or_skip libtinfo6
        install_or_skip libtinfo5
        install_or_skip lib32ncurses5-dev
        install_or_skip zlib1g-dev
