name: Build TWRP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl unzip bc bison build-essential \
          ccache clang flex libssl-dev libxml2-utils zip zlib1g-dev \
          liblz4-tool libncurses-dev python-is-python3 rsync \
          || true

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Set up repo workspace
      run: mkdir -p ~/twrp && cd ~/twrp

    - name: Cache .repo folder
      uses: actions/cache@v4
      with:
        path: ~/twrp/.repo
        key: ${{ runner.os }}-twrp-${{ hashFiles('.repo/manifest.xml') }}
        restore-keys: |
          ${{ runner.os }}-twrp-

    - name: Init TWRP repo
      run: |
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Sync sources
      run: |
        cd ~/twrp
        repo sync --force-sync --no-clone-bundle --depth=1 -j2

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git -b twrp-12.1 device/lge/caymanlm

    - name: Build TWRP
      run: |
        cd ~/twrp
        . build/envsetup.sh
        lunch omni_caymanlm-eng
        mka recoveryimage

    - name: Check recovery.img exists
      run: |
        ls -lh ~/twrp/out/target/product/caymanlm/recovery.img

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: recovery.img
        path: ~/twrp/out/target/product/caymanlm/recovery.img