name: Build TWRP Recovery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex git gnupg gperf libncurses5-dev             libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip             zlib1g-dev imagemagick openjdk-8-jdk python2 python3

      - name: Init TWRP repo
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-13.0
          repo sync -c --force-sync --no-clone-bundle --no-tags -j4

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_caymanlm-eng
          mka recoveryimage

      - name: Check recovery.img exists
        run: |
          if [ ! -f out/target/product/caymanlm/recovery.img ]; then
            echo "recovery.img not found!"
            exit 1
          fi

      - name: Upload recovery image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-caymanlm
          path: out/target/product/caymanlm/recovery.img
