name: Build TWRP Recovery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/upload-artifact@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib             g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev             libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 python3-pip repo

      - name: Configure Git identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Sync TWRP minimal manifest
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-13.0 --depth=1
          repo sync -j$(nproc --all)

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

      - name: Start build
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_caymanlm-eng
          mka recoveryimage

      - name: Upload recovery image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-recovery-img
          path: ~/twrp/out/target/product/caymanlm/recovery.img