name: Build TWRP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev         libc6-dev libncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev         libxml2-utils xsltproc unzip fontconfig python-is-python3 rsync

    - name: Install repo
      run: |
        mkdir -p ~/.bin
        curl -o ~/.bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Sync sources
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-13.0
        repo sync --force-sync -j$(nproc --all)

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Build recovery
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch twrp_caymanlm-eng
        mka recoveryimage

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp.img
        path: ~/twrp/out/target/product/caymanlm/recovery.img
