name: Build TWRP (Minimal Sync)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib           libc6-dev-i386 lib32ncurses5-dev lib32z1-dev lib32stdc++6 x11proto-core-dev libx11-dev libgl1-mesa-dev           libxml2-utils xsltproc unzip fontconfig python-is-python3 python3-pip ccache rsync libtinfo5 libncurses5

    - name: Setup ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-twrp
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Init repo (minimal)
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        sudo pip3 install repo-helper
        curl -Lo repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+x repo
        sudo mv repo /usr/local/bin/
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-13.0 --depth=1
        echo '
        [
          {
            "repository": "https://github.com/aspirus899/device_lge_caymanlm_twrp",
            "target_path": "device/lge/caymanlm",
            "branch": "main"
          }
        ]
        ' > .repo/local_manifests/local_manifest.json

    - name: Sync repo
      run: |
        cd ~/twrp
        repo sync --force-sync -c --no-tags --no-clone-bundle -j$(nproc --all)
        rm -rf .repo/project-objects .repo/projects .repo/manifests.git

    - name: Start build
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        export CCACHE_EXEC=$(which ccache)
        export USE_CCACHE=1
        ccache -M 2G
        . build/envsetup.sh
        lunch twrp_caymanlm-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-caymanlm
        path: ~/twrp/out/target/product/caymanlm/recovery.img