name: TWRP CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git wget curl unzip python3 \
          openjdk-8-jdk bc bison build-essential \
          ccache flex g++-multilib gcc-multilib \
          gnupg gperf imagemagick lib32ncurses-dev \
          lib32readline-dev lib32z1-dev liblz4-tool \
          libncurses5-dev libsdl1.2-dev libssl-dev \
          libxml2 libxml2-utils lzop pngcrush \
          rsync schedtool squashfs-tools xsltproc \
          zip zlib1g-dev

    - name: Install repo
      run: |
        mkdir -p ~/bin
        curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Init repo
      run: |
        mkdir ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Add roomservice
      run: |
        mkdir -p ~/twrp/.repo/local_manifests
        cat > ~/twrp/.repo/local_manifests/roomservice.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="aspirus899/device_lge_caymanlm_twrp" path="device/lge/caymanlm" remote="github" revision="main" />
</manifest>
EOF

    - name: Sync repo
      run: |
        cd ~/twrp
        repo sync --force-sync --no-tags --no-clone-bundle -j$(nproc)

    - name: Lunch + Build
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_caymanlm-eng
        mka recoveryimage

    - name: Upload TWRP
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: ~/twrp/out/target/product/caymanlm/recovery.img