name: Build TWRP for caymanlm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Очистити місце на runner'і
      run: |
        sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache /usr/local/share/boost \
                     /usr/local/.ghcup /usr/local/share/powershell /usr/local/lib/android
        sudo apt-get clean
        df -h

    - name: Встановлення залежностей
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex git kmod liblz4-tool \
          libncurses5-dev libssl-dev libxml2-utils lzop pngcrush rsync \
          schedtool squashfs-tools xsltproc zip zlib1g-dev \
          lib32z1 lib32stdc++6 libc6-dev-i386 g++-multilib

    - name: Встановити repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Ініціалізація репозиторію
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1

    - name: Repo Sync
      run: |
        cd ~/twrp
        ~/bin/repo sync -c --no-tags --no-clone-bundle --force-sync

    - name: Клонування пристрою
      run: |
        cd ~/twrp
        mkdir -p device/lge
        git clone https://github.com/aspirus899/android_device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Збірка TWRP
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_caymanlm-eng
        mka recoveryimage

    - name: Завантаження артефактів
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: twrp-caymanlm
        path: ~/twrp/out/target/product/caymanlm/recovery.img