name: Build TWRP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bc bison build-essential curl flex git gnupg gperf \
          liblz4-tool libncurses5-dev libssl-dev libxml2-utils \
          lzop pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev imagemagick \
          openjdk-8-jdk || sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y python-is-python3 || true
        sudo apt-get install -y libncurses-dev libtinfo-dev || true

    - name: Install repo tool
      run: |
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+rx ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Set up repo workspace
      run: mkdir -p ~/twrp

    - name: Cache .repo folder
      uses: actions/cache@v4
      with:
        path: ~/twrp/.repo
        key: ${{ runner.os }}-twrp-repo-${{ hashFiles('.repo-manifest-version') }}
        restore-keys: |
          ${{ runner.os }}-twrp-repo-

    - name: Init TWRP repo
      run: |
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Sync sources
      run: |
        cd ~/twrp
        repo sync --force-sync --no-clone-bundle -j2

    - name: Clone device tree
      run: |
        cd ~/twrp
        git clone https://github.com/aspirus899/device_lge_caymanlm_twrp.git device/lge/caymanlm

    - name: Build TWRP
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_caymanlm-eng
        mka recoveryimage

    - name: Check recovery.img exists
      run: test -f ~/twrp/out/target/product/caymanlm/recovery.img

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-caymanlm
        path: ~/twrp/out/target/product/caymanlm/recovery.img